import {
  Fish,
  TrendingUp,
  Home,
  Star,
  Eye,
  Bath,
  Component,
  Camera,
  TreePine,
  Flame,
  Earth,
  Bed,
  Mountain,
  Sun,
  Feather,
  CloudRain,
  Globe,
  Coffee,
  Heart,
  Shield,
  Moon,
  Wind,
  MapPin,
  Ship,
  DollarSign,
  Gift,
  Music,
  Phone,
  ShoppingCart,
  ShieldAlert,
  Flag,
} from "lucide-react";

interface iAppProps {
  name: string;
  title: string;
  icon: JSX.Element;
  description: string;
  id: number;
}

export const categoryItems: iAppProps[] = [
  {
    id: 0,
    name: "beach",
    description: "This Property is close to the Beach.",
    title: "Beach",
    icon: <Fish />,
  },
  {
    id: 1,
    name: "trending",
    description: "This is a Property which is trending.",
    title: "Trending",
    icon: <TrendingUp />,
  },
  {
    id: 2,
    name: "beachfront",
    description: "This is a Property close to the beachfront.",
    title: "Beachfront",
    icon: <Home />,
  },
  {
    id: 3,
    name: "earthhome",
    description: "This Property is considered an Earth Home.",
    title: "Earth Home",
    icon: <TreePine />,
  },
  {
    id: 4,
    name: "luxe",
    description: "This Property is considered luxurious.",
    title: "Luxe",
    icon: <Star />,
  },
  {
    id: 5,
    name: "amazingView",
    description: "This property has an amazing view.",
    title: "Amazing View",
    icon: <Eye />,
  },
  {
    id: 6,
    name: "design",
    description: "This property puts a big focus on design.",
    title: "Design",
    icon: <Component />,
  },
  {
    id: 7,
    name: "pool",
    description: "This property has an amazing pool.",
    title: "Pool",
    icon: <Bath />,
  },
  {
    id: 8,
    name: "tiny",
    description: "This property is considered a tiny home.",
    title: "Tiny Home",
    icon: <Home />,
  },
  {
    id: 9,
    name: "historic",
    description: "This Property is considered historic.",
    title: "Historic Home",
    icon: <Camera />,
  },
  {
    id: 10,
    name: "countryside",
    description: "This Property is located on the countryside.",
    title: "Countryside",
    icon: <TreePine />,
  },
  {
    id: 11,
    name: "omg",
    description: "This Property has a wow factor.",
    title: "WOW!",
    icon: <Flame />,
  },
  {
    id: 12,
    name: "surfing",
    description: "This Property is located near a surfing spot.",
    title: "Surfing",
    icon: <Earth />,
  },
  {
    id: 13,
    name: "cozyBed",
    description: "This Property offers a cozy bedroom.",
    title: "Cozy Bed",
    icon: <Bed />,
  },
  {
    id: 14,
    name: "mountainView",
    description: "This Property offers a stunning mountain view.",
    title: "Mountain View",
    icon: <Mountain />,
  },
  {
    id: 15,
    name: "sunset",
    description: "This Property offers beautiful sunset views.",
    title: "Sunset",
    icon: <Sun />,
  },
  {
    id: 16,
    name: "featherlight",
    description: "This Property is light as a feather.",
    title: "Featherlight",
    icon: <Feather />,
  },
  {
    id: 17,
    name: "rainyDays",
    description: "Perfect for enjoying rainy days.",
    title: "Rainy Days",
    icon: <CloudRain />,
  },
  {
    id: 18,
    name: "global",
    description: "This Property is a global sensation.",
    title: "Global",
    icon: <Globe />,
  },
  {
    id: 19,
    name: "coffeeLovers",
    description: "This Property is a paradise for coffee lovers.",
    title: "Coffee Lovers",
    icon: <Coffee />,
  },
  {
    id: 20,
    name: "romantic",
    description: "A romantic getaway property.",
    title: "Romantic",
    icon: <Heart />,
  },
  {
    id: 21,
    name: "secure",
    description: "This Property ensures top-notch security.",
    title: "Secure",
    icon: <Shield />,
  },
  {
    id: 22,
    name: "moonlight",
    description: "This Property offers stunning moonlight views.",
    title: "Moonlight",
    icon: <Moon />,
  },
  {
    id: 23,
    name: "windy",
    description: "Located in a cool and windy region.",
    title: "Windy",
    icon: <Wind />,
  },
  {
    id: 24,
    name: "urbanEscape",
    description: "This Property is an urban escape.",
    title: "Urban Escape",
    icon: <MapPin />,
  },
  {
    id: 25,
    name: "sailing",
    description: "This Property is near a sailing spot.",
    title: "Sailing",
    icon: <Ship />,
  },
  {
    id: 26,
    name: "affordable",
    description: "This Property is affordable.",
    title: "Affordable",
    icon: <DollarSign />,
  },
  {
    id: 27,
    name: "gift",
    description: "This Property is a gift for travelers.",
    title: "Gift",
    icon: <Gift />,
  },
  {
    id: 28,
    name: "musical",
    description: "This Property is close to musical venues.",
    title: "Musical",
    icon: <Music />,
  },
  {
    id: 29,
    name: "techHub",
    description: "This Property is a tech hub.",
    title: "Tech Hub",
    icon: <Phone />,
  },
  {
    id: 30,
    name: "shopping",
    description: "This Property is near a shopping center.",
    title: "Shopping",
    icon: <ShoppingCart />,
  },
  {
    id: 31,
    name: "alert",
    description: "This Property has a high-security alert system.",
    title: "Alert",
    icon: <ShieldAlert />,
  },
  {
    id: 32,
    name: "flagship",
    description: "This Property is a flagship location.",
    title: "Flagship",
    icon: <Flag />,
  },
];
